export const AUTH_USER = 'AUTH_USER';
export const NOT_AUTH_USER = 'NOT_AUTH_USER';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const UPDATE_PROFILE_PICTURE = 'UPDATE_PROFILE_PICTURE';
export const UPDATE_PROFILE_INFO = 'UPDATE_PROFILE_INFO';
